#!/bin/bash
corenum=`cat corenum`
for((j=0;j<$corenum;j=j+1))
do
    echo userspace > /sys/devices/system/cpu/cpufreq/policy$j/scaling_governor
done
for((i=1200000;i<=2200000;i=i+100000))
do
    for((j=0;j<$corenum;j=j+1))
    do
        echo $i > /sys/devices/system/cpu/cpufreq/policy$j/scaling_setspeed
    done
    #cat /sys/devices/system*/cpufreq/policy*/scaling_cur_freq
    echo freq:$i 
    time ./time_test
    echo "old meter"
    curl -s -u user:user http://192.168.1.100/port_status.shtml | grep CA 
    echo "new meter"
    python3 pa310_test.py
    echo '*********************************************************'
    echo ''
done

